### ISSUE TITLE
Zlý repozitár

### ISSUE THREAD

**Issue by CiernaOvca** [aks-2017/semestralne-zadania-semestralne-zadanie-74054-72399-1#1]
Dobrý deň.

Písala som Vám ohľadom vytvorenia viacerých repozitárov pri lagu. Teraz mi však pri prihlasovaní vyskočilo "Accepted the Semestralne Zadania assignment", po ktorom sa otvoril tento repozitár, ktorý je momentálne dostupný aj na join. 
Ten, ktorý ste upravovali ( https://github.com/aks-2017/semestralne-zadania-semestralne-zadanie-xstefankovae-xkuntovah ) však nie je prístupný a ani mi nikde nevyskakuje možnosť akceptovať assignment. Je možné premenovať tento rep. a používať ho ako hlavný? 

Vopred ďakujem za odpoveď.

**Comment by fr6nco** [comment]
Nevidite repozitar, ked otvorite URL? 

Ja ten repozitar normalne vidm, avsak je prazdny. Neviem ci ste uz nieco pushovali do tohoto repozitaru

**Comment by fr6nco** [comment]
ok, vymaazl som ten stary. Teraz ked chcete pushovat, tak musite updatenut remote.


tj git remote rm origin
a
git remote add origin https://github...tento repozitar

**Comment by CiernaOvca** [comment]
Ďakujeme.
